#!/usr/bin/env python3
"""SWE Bootstrap - Self-contained bootstrap for new projects.

Resolves plugin root from __file__. Operates on os.getcwd().
Creates minimal directory structure and config files needed
before /swe-init or /swe-scaffold-project can run.

Guards:
- Exit if .serena/swe-bypass.json exists (SWE bypassed)
- Exit if .serena/swe-setup-complete.json has complete: true (already initialized)
- Exit if .serena/swe-setup-complete.json has bootstrapped: true (already bootstrapped)
"""

import os
import sys
import json
import re
from datetime import datetime
from collections import Counter

# Resolve plugin root from this script's location
PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories to skip when scanning for languages
SKIP_DIRS = {'.git', 'node_modules', 'vendor', '.serena', '.claude', '__pycache__',
             '.vscode', '.idea', 'dist', 'build', '.cache'}

# Extension to Serena language name mapping
EXT_TO_LANGUAGE = {
    '.php': 'php',
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'typescript',
    '.jsx': 'typescript',
    '.py': 'python',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.go': 'go',
    '.java': 'java',
    '.cs': 'csharp',
    '.cpp': 'cpp',
    '.c': 'c',
    '.swift': 'swift',
    '.kt': 'kotlin',
}


def get_plugin_version():
    """Read version from plugin.json."""
    plugin_json = os.path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json')
    try:
        with open(plugin_json) as f:
            data = json.load(f)
        return data.get('version', 'unknown')
    except (IOError, json.JSONDecodeError):
        return 'unknown'


def detect_languages(project_root):
    """Walk project tree and detect languages from file extensions."""
    ext_counts = Counter()
    for dirpath, dirnames, filenames in os.walk(project_root):
        # Skip ignored directories (modifies in-place for os.walk)
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for filename in filenames:
            _, ext = os.path.splitext(filename)
            if ext in EXT_TO_LANGUAGE:
                ext_counts[ext] += 1

    languages = set()
    for ext, _count in ext_counts.items():
        languages.add(EXT_TO_LANGUAGE[ext])

    # Always include markdown
    languages.add('markdown')
    return sorted(languages)


def create_project_yml(project_root, languages):
    """Create .serena/project.yml with detected languages. Skip if exists."""
    yml_path = os.path.join(project_root, '.serena', 'project.yml')
    if os.path.exists(yml_path):
        return False

    lang_lines = '\n'.join(f'  - {lang}' for lang in languages)
    content = f"""# Auto-generated by SWE bootstrap
# Detected languages from project file extensions
languages:
{lang_lines}

# Exclude session Working Memory files from list_memories output.
# WM files are accessed via the swe-wm MCP server, not Serena's memory API.
ignored_memory_patterns: ["WM_.*"]
"""
    with open(yml_path, 'w') as f:
        f.write(content)
    return True


def ensure_memory_paths_conf(project_root, extra_paths=None):
    """Create or update .serena/memory-paths.conf with SWE memory paths.

    SWE required paths are always placed at the top of the file (after the
    header comments), before any user-defined paths.

    Args:
        project_root: Project root directory
        extra_paths: Optional list of additional paths (e.g. ['./docs:ro'])
    """
    conf_path = os.path.join(project_root, '.serena', 'memory-paths.conf')
    required_lines = ['./.serena/memory', './.serena/memories']

    if os.path.exists(conf_path):
        with open(conf_path) as f:
            lines = f.read().splitlines()

        # Separate comment lines from path lines
        comment_lines = []
        path_lines = []
        for line in lines:
            if line.startswith('#') or line.strip() == '':
                comment_lines.append(line)
            else:
                path_lines.append(line)

        missing = [p for p in required_lines if p not in path_lines]
        if extra_paths:
            missing.extend(p for p in extra_paths if p not in path_lines)
        if not missing:
            return False  # All paths already present

        # Insert missing required paths at top, extra paths at bottom
        missing_required = [p for p in missing if p in required_lines]
        missing_extra = [p for p in missing if p not in required_lines]
        new_path_lines = missing_required + path_lines + missing_extra

        with open(conf_path, 'w') as f:
            for line in comment_lines:
                f.write(f'{line}\n')
            for line in new_path_lines:
                f.write(f'{line}\n')
        return True

    all_lines = required_lines + (extra_paths or [])
    content = "# Serena memory paths configuration\n"
    content += "# Each line is a path (relative to project root) containing memory files\n"
    for line in all_lines:
        content += f"{line}\n"
    with open(conf_path, 'w') as f:
        f.write(content)
    return True


def copy_template_memories(project_root):
    """Copy template memories from plugin to project .serena/memory/."""
    templates_dir = os.path.join(PLUGIN_ROOT, 'memories', 'templates')
    target_dir = os.path.join(project_root, '.serena', 'memory')
    copied = []

    if not os.path.isdir(templates_dir):
        return copied

    for filename in os.listdir(templates_dir):
        if not filename.endswith('.md'):
            continue
        source = os.path.join(templates_dir, filename)
        target = os.path.join(target_dir, filename)
        if os.path.exists(target):
            continue  # Don't overwrite existing
        with open(source) as f:
            content = f.read()
        with open(target, 'w') as f:
            f.write(content)
        copied.append(filename)

    return copied


def migrate_auto_memory(project_root):
    """Migrate auto-memory files from ~/.claude/projects/<encoded>/memory/ to .serena/memory/.

    Reorganizes flat files into typed subdirectories with uppercase names:
      feedback_test.md  → feedback/FEEDBACK_TEST.md
      user_role.md      → user/USER_ROLE.md
      project_notes.md  → project/PROJECT_NOTES.md
      reference_api.md  → ref/REF_API.md
      SPEC_Foo.md       → spec/SPEC_Foo.md
      other.md          → OTHER.md (root, uppercased)

    MEMORY.md is merged (unique entries appended with updated paths).

    Returns list of migrated filenames (new paths).
    """
    target_dir = os.path.join(project_root, '.serena', 'memory')

    # Determine auto-memory source path
    encoded_both = project_root.replace('/', '-').replace('_', '-')
    if encoded_both.startswith('-'):
        encoded_both = encoded_both  # keep leading dash
    auto_dir = os.path.join(os.path.expanduser('~'), '.claude', 'projects', encoded_both, 'memory')

    if not os.path.isdir(auto_dir) or os.path.islink(auto_dir):
        # Try underscore-preserving encoding (older Claude Code)
        encoded_slash = project_root.replace('/', '-')
        auto_dir = os.path.join(os.path.expanduser('~'), '.claude', 'projects', encoded_slash, 'memory')
        if not os.path.isdir(auto_dir) or os.path.islink(auto_dir):
            return []

    # Prefix-to-subdirectory mapping
    PREFIX_MAP = {
        'feedback_': ('feedback', 'FEEDBACK_'),
        'user_': ('user', 'USER_'),
        'project_': ('project', 'PROJECT_'),
        'reference_': ('ref', 'REF_'),
    }

    migrated = []
    memory_md_source = None

    for filename in os.listdir(auto_dir):
        if not filename.endswith('.md'):
            continue
        source = os.path.join(auto_dir, filename)
        if not os.path.isfile(source):
            continue

        # Handle MEMORY.md separately
        if filename == 'MEMORY.md':
            memory_md_source = source
            continue

        # Determine target subdir and new name
        subdir = ''
        newname = filename
        matched = False

        # Check SPEC_ first (already uppercase, just move to subdir)
        if filename.startswith('SPEC_'):
            subdir = 'spec'
            newname = filename
            matched = True

        if not matched:
            for prefix, (target_subdir, new_prefix) in PREFIX_MAP.items():
                if filename.startswith(prefix):
                    subdir = target_subdir
                    # Strip old prefix, uppercase the rest, prepend new prefix
                    rest = filename[len(prefix):]
                    name_part = rest.rsplit('.md', 1)[0]
                    newname = new_prefix + name_part.upper() + '.md'
                    matched = True
                    break

        if not matched:
            # Unknown prefix — uppercase and keep at root
            name_part = filename.rsplit('.md', 1)[0]
            newname = name_part.upper() + '.md'

        # Create subdirectory if needed
        if subdir:
            target_subdir_path = os.path.join(target_dir, subdir)
            os.makedirs(target_subdir_path, exist_ok=True)
            target = os.path.join(target_subdir_path, newname)
            rel_path = f"{subdir}/{newname}"
        else:
            target = os.path.join(target_dir, newname)
            rel_path = newname

        if not os.path.exists(target):
            with open(source) as f:
                content = f.read()
            with open(target, 'w') as f:
                f.write(content)
            migrated.append(rel_path)

    # Merge MEMORY.md
    if memory_md_source:
        target_memory = os.path.join(target_dir, 'MEMORY.md')
        _merge_memory_md(memory_md_source, target_memory, project_root)
        migrated.append('MEMORY.md (merged)')

    return migrated


def _merge_memory_md(source_path, target_path, project_root):
    """Merge auto-memory MEMORY.md entries into target, rewriting paths to match new structure."""
    PREFIX_MAP = {
        'feedback_': 'feedback/FEEDBACK_',
        'user_': 'user/USER_',
        'project_': 'project/PROJECT_',
        'reference_': 'ref/REF_',
    }

    with open(source_path) as f:
        source_lines = f.readlines()

    # Read existing target content (may not exist yet)
    target_content = ''
    if os.path.exists(target_path):
        with open(target_path) as f:
            target_content = f.read()

    new_entries = []
    for line in source_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue

        # Rewrite link paths in the line
        rewritten = line
        for old_prefix, new_prefix in PREFIX_MAP.items():
            # Match markdown links like ](feedback_test.md)
            pattern = re.escape(old_prefix) + r'([^)]+\.md)'
            def _rewrite(m):
                rest = m.group(1)
                name_part = rest.rsplit('.md', 1)[0]
                return new_prefix + name_part.upper() + '.md'
            rewritten = re.sub(pattern, _rewrite, rewritten)

        # Handle SPEC_ links — just add spec/ prefix
        rewritten = re.sub(r'\]\((SPEC_[^)]+)\)', r'](spec/\1)', rewritten)

        # Check if this entry (by link target) already exists in target
        link_match = re.search(r'\]\(([^)]+)\)', rewritten)
        if link_match:
            link_target = link_match.group(1)
            if link_target not in target_content:
                new_entries.append(rewritten)

    if new_entries:
        with open(target_path, 'a') as f:
            f.write('\n## Migrated from Auto-Memory\n')
            for entry in new_entries:
                f.write(entry if entry.endswith('\n') else entry + '\n')


def prompt_extra_memory_paths():
    """Prompt user for additional directories Serena should access.

    Returns list of paths like ['./docs:ro', './src/config'].
    """
    extra = []
    print("\n--- Additional Serena Memory Paths ---")
    print("Serena can read folders in your project (e.g. ./docs, ./src/config).")
    print("Append :ro for read-only access. Leave blank to skip.\n")
    while True:
        path = input("  Add folder (or press Enter to finish): ").strip()
        if not path:
            break
        # Normalize: ensure starts with ./
        if not path.startswith('./') and not path.startswith('/'):
            path = './' + path
        ro = input(f"  Read-only? (y/N): ").strip().lower()
        if ro in ('y', 'yes'):
            if not path.endswith(':ro'):
                path += ':ro'
        extra.append(path)
        print(f"    Added: {path}")
    return extra


def inject_claude_prefix(project_root):
    """Prepend CLAUDE_PREFIX.md to the project's CLAUDE.md if not already present."""
    prefix_path = os.path.join(PLUGIN_ROOT, 'scripts', 'CLAUDE_PREFIX.md')
    claude_md_path = os.path.join(project_root, 'CLAUDE.md')

    if not os.path.exists(prefix_path):
        return False

    with open(prefix_path, 'r') as f:
        prefix_content = f.read().rstrip('\n')

    # Marker to detect if already injected
    marker = 'MANDATORY ENTRY POINT'

    if os.path.exists(claude_md_path):
        with open(claude_md_path, 'r') as f:
            existing = f.read()
        if marker in existing:
            return False  # Already has the prefix
        # Prepend
        with open(claude_md_path, 'w') as f:
            f.write(prefix_content + '\n\n' + existing)
    else:
        with open(claude_md_path, 'w') as f:
            f.write(prefix_content + '\n')

    return True


def ensure_serena_gitignore(project_root):
    """Create .serena/.gitignore for runtime file exclusions."""
    gitignore_path = os.path.join(project_root, '.serena', '.gitignore')
    if os.path.exists(gitignore_path):
        return False

    content = """/cache

# Stream data (ephemeral, session-specific)
streams/

# Working memory files (session-specific, ephemeral)
memories/WM_*.md
memories/LITE_MODE_*.md

# SWE runtime state
swe-state/
swe-bypass.json
swe-setup-complete.json

# Keep everything else (feature memories, specs, etc.)
!memory/
!memory/**/*.md
!memories/
!/memory-paths.conf
"""
    with open(gitignore_path, 'w') as f:
        f.write(content)
    return True


def update_gitignore(project_root):
    """Add SWE-specific entries to .gitignore if not already present."""
    gitignore_path = os.path.join(project_root, '.gitignore')
    entries = [
        '.serena/swe-bypass.json',
        '.serena/swe-setup-complete.json',
        '.serena/swe-state/',
        '',
        '# Override global .serena/* ignore — un-ignore project memories',
        '!.serena/memory/',
        '!.serena/memory/**/*.md',
        '!.serena/memories/',
        '!.serena/memories/**/*.md',
        '.serena/memories/WM_*.md',
    ]

    existing_content = ''
    if os.path.exists(gitignore_path):
        with open(gitignore_path) as f:
            existing_content = f.read()

    # Check if already configured (use the negation pattern as marker)
    if '!.serena/memory/' in existing_content:
        return False

    with open(gitignore_path, 'a') as f:
        f.write('\n# SWE workflow engine\n')
        for entry in entries:
            f.write(f'{entry}\n')
    return True


def main():
    project_root = os.getcwd()

    # Guard: Check bypass
    bypass_file = os.path.join(project_root, '.serena', 'swe-bypass.json')
    if os.path.exists(bypass_file):
        print("SWE bypassed for this project. Remove .serena/swe-bypass.json to re-enable.")
        sys.exit(0)

    # Guard: Check if already fully initialized
    setup_file = os.path.join(project_root, '.serena', 'swe-setup-complete.json')
    if os.path.exists(setup_file):
        try:
            with open(setup_file) as f:
                setup_data = json.load(f)
            if setup_data.get('complete'):
                print("Already fully initialized. Nothing to do.")
                sys.exit(0)
            if setup_data.get('bootstrapped'):
                print("Already bootstrapped. Run /swe-init to complete setup (recommended), or /swe-scaffold-project for manual setup.")
                sys.exit(0)
        except (json.JSONDecodeError, IOError):
            pass  # Corrupt file — proceed with bootstrap

    # Create directories
    dirs = [
        os.path.join(project_root, '.serena'),
                os.path.join(project_root, '.serena', 'memory'),
        os.path.join(project_root, '.serena', 'memory', 'feature'),
        os.path.join(project_root, '.serena', 'memories'),
        os.path.join(project_root, '.serena', 'swe-state'),
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Detect languages
    languages = detect_languages(project_root)

    # Create project.yml
    yml_created = create_project_yml(project_root, languages)

    # Prompt for additional memory paths
    extra_paths = prompt_extra_memory_paths()

    # Create/update memory-paths.conf
    conf_updated = ensure_memory_paths_conf(project_root, extra_paths=extra_paths)

    # Migrate existing auto-memory files (before template copy to avoid conflicts)
    migrated_files = migrate_auto_memory(project_root)

    # Copy template memories (skips files that already exist from migration)
    copied_templates = copy_template_memories(project_root)

    # Create swe-setup-complete.json (bootstrapped, not complete)
    version = get_plugin_version()
    setup_data = {
        "complete": False,
        "bootstrapped": True,
        "bootstrapped_at": datetime.now().isoformat(),
        "version": version,
        "needs_full_init": True,
    }
    with open(setup_file, 'w') as f:
        json.dump(setup_data, f, indent=2)

    # Create README.md only if zero non-dot files exist
    non_dot_files = [f for f in os.listdir(project_root) if not f.startswith('.')]
    if not non_dot_files:
        readme_path = os.path.join(project_root, 'README.md')
        if not os.path.exists(readme_path):
            with open(readme_path, 'w') as f:
                f.write('# Project\n')

    # Create .serena/.gitignore
    serena_gitignore_created = ensure_serena_gitignore(project_root)

    # Update project .gitignore
    gitignore_updated = update_gitignore(project_root)

    # Inject CLAUDE_PREFIX.md into CLAUDE.md
    claude_prefix_injected = inject_claude_prefix(project_root)

    # Report
    print("SWE Bootstrap Complete")
    print(f"  Plugin version: {version}")
    print(f"  Languages detected: {', '.join(languages)}")
    print(f"  project.yml: {'created' if yml_created else 'already exists'}")
    print(f"  memory-paths.conf: {'updated' if conf_updated else 'already configured'}")
    if extra_paths:
        print(f"  Extra paths added: {', '.join(extra_paths)}")
    if migrated_files:
        print(f"  Auto-memory migrated: {', '.join(migrated_files)}")
    if copied_templates:
        print(f"  Templates copied: {', '.join(copied_templates)}")
    print(f"  .serena/.gitignore: {'created' if serena_gitignore_created else 'already exists'}")
    print(f"  .gitignore: {'updated' if gitignore_updated else 'already configured'}")
    print(f"  CLAUDE.md: {'prefix injected' if claude_prefix_injected else 'already configured'}")
    print(f"  Setup status: bootstrapped (run /swe-init to complete, or /swe-scaffold-project for manual setup)")


if __name__ == '__main__':
    main()
