#!/usr/bin/env python3
"""SWE Bootstrap - Self-contained bootstrap for new projects.

Resolves plugin root from __file__. Operates on os.getcwd().
Creates minimal directory structure and config files needed
before /swe-init or /swe-scaffold-project can run.

Guards:
- Exit if .serena/swe-bypass.json exists (SWE bypassed)
- Exit if .serena/swe-setup-complete.json has complete: true (already initialized)
- Exit if .serena/swe-setup-complete.json has bootstrapped: true (already bootstrapped)
"""

import os
import sys
import json
from datetime import datetime
from collections import Counter

# Resolve plugin root from this script's location
PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories to skip when scanning for languages
SKIP_DIRS = {'.git', 'node_modules', 'vendor', '.serena', '.claude', '__pycache__',
             '.vscode', '.idea', 'dist', 'build', '.cache'}

# Extension to Serena language name mapping
EXT_TO_LANGUAGE = {
    '.php': 'php',
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'typescript',
    '.jsx': 'typescript',
    '.py': 'python',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.go': 'go',
    '.java': 'java',
    '.cs': 'csharp',
    '.cpp': 'cpp',
    '.c': 'c',
    '.swift': 'swift',
    '.kt': 'kotlin',
}


def get_plugin_version():
    """Read version from plugin.json."""
    plugin_json = os.path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json')
    try:
        with open(plugin_json) as f:
            data = json.load(f)
        return data.get('version', 'unknown')
    except (IOError, json.JSONDecodeError):
        return 'unknown'


def detect_languages(project_root):
    """Walk project tree and detect languages from file extensions."""
    ext_counts = Counter()
    for dirpath, dirnames, filenames in os.walk(project_root):
        # Skip ignored directories (modifies in-place for os.walk)
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for filename in filenames:
            _, ext = os.path.splitext(filename)
            if ext in EXT_TO_LANGUAGE:
                ext_counts[ext] += 1

    languages = set()
    for ext, _count in ext_counts.items():
        languages.add(EXT_TO_LANGUAGE[ext])

    # Always include markdown
    languages.add('markdown')
    return sorted(languages)


def create_project_yml(project_root, languages):
    """Create .serena/project.yml with detected languages. Skip if exists."""
    yml_path = os.path.join(project_root, '.serena', 'project.yml')
    if os.path.exists(yml_path):
        return False

    lang_lines = '\n'.join(f'  - {lang}' for lang in languages)
    content = f"""# Auto-generated by SWE bootstrap
# Detected languages from project file extensions
languages:
{lang_lines}
"""
    with open(yml_path, 'w') as f:
        f.write(content)
    return True


def ensure_memory_paths_conf(project_root, extra_paths=None):
    """Create or update .serena/memory-paths.conf with SWE memory paths.

    SWE required paths are always placed at the top of the file (after the
    header comments), before any user-defined paths.

    Args:
        project_root: Project root directory
        extra_paths: Optional list of additional paths (e.g. ['./docs:ro'])
    """
    conf_path = os.path.join(project_root, '.serena', 'memory-paths.conf')
    required_lines = ['./.serena/memory', './.serena/memories']

    if os.path.exists(conf_path):
        with open(conf_path) as f:
            lines = f.read().splitlines()

        # Separate comment lines from path lines
        comment_lines = []
        path_lines = []
        for line in lines:
            if line.startswith('#') or line.strip() == '':
                comment_lines.append(line)
            else:
                path_lines.append(line)

        missing = [p for p in required_lines if p not in path_lines]
        if extra_paths:
            missing.extend(p for p in extra_paths if p not in path_lines)
        if not missing:
            return False  # All paths already present

        # Insert missing required paths at top, extra paths at bottom
        missing_required = [p for p in missing if p in required_lines]
        missing_extra = [p for p in missing if p not in required_lines]
        new_path_lines = missing_required + path_lines + missing_extra

        with open(conf_path, 'w') as f:
            for line in comment_lines:
                f.write(f'{line}\n')
            for line in new_path_lines:
                f.write(f'{line}\n')
        return True

    all_lines = required_lines + (extra_paths or [])
    content = "# Serena memory paths configuration\n"
    content += "# Each line is a path (relative to project root) containing memory files\n"
    for line in all_lines:
        content += f"{line}\n"
    with open(conf_path, 'w') as f:
        f.write(content)
    return True


def copy_template_memories(project_root):
    """Copy template memories from plugin to project .serena/swe/."""
    templates_dir = os.path.join(PLUGIN_ROOT, 'memories', 'templates')
    target_dir = os.path.join(project_root, '.serena', 'swe')
    copied = []

    if not os.path.isdir(templates_dir):
        return copied

    for filename in os.listdir(templates_dir):
        if not filename.endswith('.md'):
            continue
        source = os.path.join(templates_dir, filename)
        target = os.path.join(target_dir, filename)
        if os.path.exists(target):
            continue  # Don't overwrite existing
        with open(source) as f:
            content = f.read()
        with open(target, 'w') as f:
            f.write(content)
        copied.append(filename)

    return copied


def prompt_extra_memory_paths():
    """Prompt user for additional directories Serena should access.

    Returns list of paths like ['./docs:ro', './src/config'].
    """
    extra = []
    print("\n--- Additional Serena Memory Paths ---")
    print("Serena can read folders in your project (e.g. ./docs, ./src/config).")
    print("Append :ro for read-only access. Leave blank to skip.\n")
    while True:
        path = input("  Add folder (or press Enter to finish): ").strip()
        if not path:
            break
        # Normalize: ensure starts with ./
        if not path.startswith('./') and not path.startswith('/'):
            path = './' + path
        ro = input(f"  Read-only? (y/N): ").strip().lower()
        if ro in ('y', 'yes'):
            if not path.endswith(':ro'):
                path += ':ro'
        extra.append(path)
        print(f"    Added: {path}")
    return extra


def inject_claude_prefix(project_root):
    """Prepend CLAUDE_PREFIX.md to the project's CLAUDE.md if not already present."""
    prefix_path = os.path.join(PLUGIN_ROOT, 'scripts', 'CLAUDE_PREFIX.md')
    claude_md_path = os.path.join(project_root, 'CLAUDE.md')

    if not os.path.exists(prefix_path):
        return False

    with open(prefix_path, 'r') as f:
        prefix_content = f.read().rstrip('\n')

    # Marker to detect if already injected
    marker = 'MANDATORY ENTRY POINT'

    if os.path.exists(claude_md_path):
        with open(claude_md_path, 'r') as f:
            existing = f.read()
        if marker in existing:
            return False  # Already has the prefix
        # Prepend
        with open(claude_md_path, 'w') as f:
            f.write(prefix_content + '\n\n' + existing)
    else:
        with open(claude_md_path, 'w') as f:
            f.write(prefix_content + '\n')

    return True


def ensure_serena_gitignore(project_root):
    """Create .serena/.gitignore for runtime file exclusions."""
    gitignore_path = os.path.join(project_root, '.serena', '.gitignore')
    if os.path.exists(gitignore_path):
        return False

    content = """/cache

# Stream data (ephemeral, session-specific)
streams/

# Working memory files (session-specific, ephemeral)
memories/WM_*.md
memories/LITE_MODE_*.md

# SWE runtime state
swe-state/
swe-bypass.json
swe-setup-complete.json

# Keep everything else (feature memories, specs, etc.)
!swe/
!swe/**/*.md
!memories/
!/memory-paths.conf
"""
    with open(gitignore_path, 'w') as f:
        f.write(content)
    return True


def update_gitignore(project_root):
    """Add SWE-specific entries to .gitignore if not already present."""
    gitignore_path = os.path.join(project_root, '.gitignore')
    entries = [
        '.serena/swe-bypass.json',
        '.serena/swe-setup-complete.json',
        '.serena/swe-state/',
        '',
        '# Override global .serena/* ignore — un-ignore swe memories',
        '!.serena/swe/',
        '!.serena/swe/**/*.md',
        '!.serena/memories/',
        '!.serena/memories/**/*.md',
        '.serena/memories/WM_*.md',
    ]

    existing_content = ''
    if os.path.exists(gitignore_path):
        with open(gitignore_path) as f:
            existing_content = f.read()

    # Check if already configured (use the negation pattern as marker)
    if '!.serena/swe/' in existing_content:
        return False

    with open(gitignore_path, 'a') as f:
        f.write('\n# SWE workflow engine\n')
        for entry in entries:
            f.write(f'{entry}\n')
    return True


def main():
    project_root = os.getcwd()

    # Guard: Check bypass
    bypass_file = os.path.join(project_root, '.serena', 'swe-bypass.json')
    if os.path.exists(bypass_file):
        print("SWE bypassed for this project. Remove .serena/swe-bypass.json to re-enable.")
        sys.exit(0)

    # Guard: Check if already fully initialized
    setup_file = os.path.join(project_root, '.serena', 'swe-setup-complete.json')
    if os.path.exists(setup_file):
        try:
            with open(setup_file) as f:
                setup_data = json.load(f)
            if setup_data.get('complete'):
                print("Already fully initialized. Nothing to do.")
                sys.exit(0)
            if setup_data.get('bootstrapped'):
                print("Already bootstrapped. Run /swe-init or /swe-scaffold-project to complete setup.")
                sys.exit(0)
        except (json.JSONDecodeError, IOError):
            pass  # Corrupt file — proceed with bootstrap

    # Create directories
    dirs = [
        os.path.join(project_root, '.serena'),
                os.path.join(project_root, '.serena', 'memory'),
        os.path.join(project_root, '.serena', 'swe'),
        os.path.join(project_root, '.serena', 'swe', 'feature'),
        os.path.join(project_root, '.serena', 'memories'),
        os.path.join(project_root, '.serena', 'swe-state'),
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Detect languages
    languages = detect_languages(project_root)

    # Create project.yml
    yml_created = create_project_yml(project_root, languages)

    # Prompt for additional memory paths
    extra_paths = prompt_extra_memory_paths()

    # Create/update memory-paths.conf
    conf_updated = ensure_memory_paths_conf(project_root, extra_paths=extra_paths)

    # Copy template memories
    copied_templates = copy_template_memories(project_root)

    # Create swe-setup-complete.json (bootstrapped, not complete)
    version = get_plugin_version()
    setup_data = {
        "complete": False,
        "bootstrapped": True,
        "bootstrapped_at": datetime.now().isoformat(),
        "version": version,
        "needs_full_init": True,
    }
    with open(setup_file, 'w') as f:
        json.dump(setup_data, f, indent=2)

    # Create README.md only if zero non-dot files exist
    non_dot_files = [f for f in os.listdir(project_root) if not f.startswith('.')]
    if not non_dot_files:
        readme_path = os.path.join(project_root, 'README.md')
        if not os.path.exists(readme_path):
            with open(readme_path, 'w') as f:
                f.write('# Project\n')

    # Create .serena/.gitignore
    serena_gitignore_created = ensure_serena_gitignore(project_root)

    # Update project .gitignore
    gitignore_updated = update_gitignore(project_root)

    # Inject CLAUDE_PREFIX.md into CLAUDE.md
    claude_prefix_injected = inject_claude_prefix(project_root)

    # Report
    print("SWE Bootstrap Complete")
    print(f"  Plugin version: {version}")
    print(f"  Languages detected: {', '.join(languages)}")
    print(f"  project.yml: {'created' if yml_created else 'already exists'}")
    print(f"  memory-paths.conf: {'updated' if conf_updated else 'already configured'}")
    if extra_paths:
        print(f"  Extra paths added: {', '.join(extra_paths)}")
    if copied_templates:
        print(f"  Templates copied: {', '.join(copied_templates)}")
    print(f"  .serena/.gitignore: {'created' if serena_gitignore_created else 'already exists'}")
    print(f"  .gitignore: {'updated' if gitignore_updated else 'already configured'}")
    print(f"  CLAUDE.md: {'prefix injected' if claude_prefix_injected else 'already configured'}")
    print(f"  Setup status: bootstrapped (needs /swe-scaffold-project to complete)")


if __name__ == '__main__':
    main()
